o.maisour/Home work 1
desfarik/it-academy-FD2-128-23 pull request #21
Opened 2023-02-22 07:21 UTC by 1986maisuromar

2023-02-27 17:51 UTC, 1986maisuromar commented
ready

2023-02-28 07:40 UTC, Dima-Astreyko commented
Название ветки неправильное

2023-02-28 07:41 UTC, Dima-Astreyko commented
Почему ты не создал свою папку как требовалось

2023-02-28 07:59 UTC, Dima-Astreyko requested changes
пока не поменяешь папочную структура это нельзя будет мержить

2023-02-28 07:59 UTC, Dima-Astreyko commented on homework/homeWork-1/homeWork_1.css
> +video {
правильней было бы вынести это в отдельный файл

2023-02-28 07:59 UTC, Dima-Astreyko commented on homework/homeWork-1/index.html
> +        <div class="header_wrapper">
нужно больше врапперов богу врапперов

2023-02-28 07:59 UTC, Dima-Astreyko commented on homework/homeWork-1/index.html
> +      <div class="kcal_avail">
классый пишутся в другой нотации

2023-02-28 07:59 UTC, Dima-Astreyko commented on homework/homeWork-1/index.html
> +          <div class="nutrition_water-wrapper">
опять миллионы врапперов

2023-02-28 07:59 UTC, Dima-Astreyko commented on homework/homeWork-1/index.html
> +                <span style="color: #4166f5">Water</span> 0.9L (75%)
стили добавлять только через css файл

2023-02-28 07:59 UTC, Dima-Astreyko commented on homework/homeWork-1/index.html
> +                alt="negetive button"
мог уже и в кнопку обвернуть раз это кнопка

2023-02-28 07:59 UTC, Dima-Astreyko commented on homework/homeWork-1/index.html
> +              <p class="brek">Breakfast</p>
это врядли параграфы, это скорее спаны по смыслу

2023-02-28 07:59 UTC, Dima-Astreyko commented on homework/homeWork-1/index.html
> +                <p class="drin_ty">Coffe with milk 100 g</p>
оуу, а зачем на каждый тип ты свой класс создал?

2023-02-28 07:59 UTC, Dima-Astreyko commented on homework/homeWork-1/index.html
> +        <div class="nutrition_Lunch">
нужно было сделать через максимальное переиспользование классов, у тебя блоки отлючаются лишь цветом заголовков, все остальное одинаковое. не нужно было под каждый создвать свой класс

2023-02-28 07:59 UTC, Dima-Astreyko commented on homework/homeWork-1/homeWork_1.css
> +   padding-left: 20px;
лучше было обвернуть весь скролируемый контент в этот враппер, а не каждый блок в него обворачивать

2023-02-28 07:59 UTC, Dima-Astreyko commented on homework/homeWork-1/homeWork_1.css
> +   background-color: #C4C4C4;
неправильный цвет

2023-02-28 07:59 UTC, Dima-Astreyko commented on homework/homeWork-1/homeWork_1.css
> +   padding-top: 114px;
отсутп больше 30 - ошибка 
нужно было как-то по другом это сделать

2023-02-28 07:59 UTC, Dima-Astreyko commented on homework/homeWork-1/homeWork_1.css
> +   /* background: linear-gradient(#9FE860, #50CE3B); */
лишний код

2023-02-28 07:59 UTC, Dima-Astreyko commented on homework/homeWork-1/homeWork_1.css
> +   padding-left: 5%;
оступ в %?

2023-02-28 07:59 UTC, Dima-Astreyko commented on homework/homeWork-1/homeWork_1.css
> +   padding-top: 19px;
отсупы должны быть кратны 4 или 5

2023-02-28 07:59 UTC, Dima-Astreyko commented on homework/homeWork-1/homeWork_1.css
> +   border-radius: 91.86px;
что это такое?

2023-02-28 07:59 UTC, Dima-Astreyko commented on homework/homeWork-1/homeWork_1.css
> +   margin-top: -95px;
выглядить как гвоздями подняли вверх, нужно было за счет другой композиции верстки это делать

2023-02-28 07:59 UTC, Dima-Astreyko commented on homework/homeWork-1/homeWork_1.css
> +   height: 60px;
высота здесь излишня, если ее убрать ничего не произойдет
следовательно - она не нужна
на будущее, задание высоты почти всегда будет приводить к проблемам

2023-02-28 07:59 UTC, Dima-Astreyko commented on homework/homeWork-1/homeWork_1.css
> +.g_p_o_c{
что за классные имена классов

2023-02-28 07:59 UTC, Dima-Astreyko commented on homework/homeWork-1/homeWork_1.css
> +   margin-bottom: 16px;
а можно было как-то абстрктно назвать блок, и не писать кучу кода тут
и кучу раззного кода в html

2023-02-28 07:59 UTC, Dima-Astreyko commented on homework/homeWork-1/homeWork_1.css
> +height: 180px;
что с выравниванием

2023-03-10 16:17 UTC, closed without merging